### ISSUE TITLE
SMIU PTBR Translation

### ISSUE THREAD

**Issue by Lordben-wan** [sharkster91/SMUI#22]
Sorry if here is the wrong place, but didn't find other way to reach you. I've completed translation for PTBR on version of 24 de ago. às 0:53. Feel free if you want to include on your mod.

SMIU
[PTBR.zip](https://github.com/sharkster91/SMUI/files/9470853/PTBR.zip)

**Comment by sharkster91** [comment]
Thank you, this is the right place. I will take a look.
