### ISSUE TITLE
bug on ur shark law enforcement

### ISSUE THREAD

**Issue by realgdubz** [sharkster91/SMUI#24]
I tried to add you and leave a comment but I didnt know where to post this but here.

Fatal Error] :93:52: The element type "itemGUID" must be terminated by the matching end-tag "</itemGUID>".
ERROR: General     , 1662118501305> 85,820,796> Exception parsing filename: C:\pzserver\steamapps\workshop\content\108600\2856282437\mods\Shark's Law Enforcement Overhaul\media\clothing\clothing.xml
ERROR: General     , 1662118501306> 85,820,798> zombie.util.PZXmlParserException: Exception thrown while parsing XML file "C:\pzserver\steamapps\workshop\content\108600\2856282437\mods\Shark's Law Enforcement Overhaul\media\clothing\clothing.xml"
  Caused by:
    org.xml.sax.SAXParseException; lineNumber: 93; columnNumber: 52; The element type "itemGUID" must be terminated by the matching end-tag "</itemGUID>".

**Comment by sharkster91** [comment]
I only respond here as its the only place to properly track bugs.

Can I have the full log? I'll check this out now.
