### ISSUE TITLE
Invisible large backpacks when player wears them.

### ISSUE THREAD

**Issue by Steelherd** [sharkster91/SMUI#27]
I can see them on the zombies, I can see them when they're equipped to primary or secondary and when they're on the ground but when worn on the back they are invisible. This started happening a couple weeks ago.

![Untitled](https://user-images.githubusercontent.com/92630794/189162164-d1be9a24-30dc-4967-b8a8-21228983cbf5.png)

![Untitled1](https://user-images.githubusercontent.com/92630794/189162180-4448e85e-137b-41aa-9c9a-eedac6a03830.png)

**Comment by sharkster91** [comment]
Nice, this is the first time anyone has ever specified which it is and
what's happening. I'll take a look.

**Comment by Steelherd** [comment]
Awesome, thanks! I dont know if the military large backpack is also affected as I havent been able to find one, but I will keep looking and update you if needed.

**Comment by sharkster91** [comment]
This looks like a mod conflict since its reverting to its vanilla name and
the mesh is gone. I'll need a mod list too.

**Comment by Steelherd** [comment]
Since you confirmed its a conflict, I went through my mod list and checked any that adds/modifies clothing.

the culprit appears to be ClothesBox Redux- https://steamcommunity.com/sharedfiles/filedetails/?id=2847911733

**Comment by sharkster91** [comment]
Thanks, a fix should be coming soon then.

**Comment by Steelherd** [comment]
Just to update you, I removed that mod when I found out it was causing the issue and I no longer use it but the same issue started recently with the invisible large backpack. after more testing, the military overhaul mod seems to be the only one overwriting that specific bag and I dont think any of the other mods I use are interacting with that specific bag.

**Comment by sharkster91** [comment]
Yep, I figured as much. Thanks for letting me know.

**Comment by chernobyl-ctrl** [comment]
Using a cheat mod I got the vanilla backpack (overwritten by your mod) and Alice's, these two are identical but the alice one works but the vanilla one doesn't (3d model) ...

**Comment by Steelherd** [comment]
So a weird element I learned, when my female character wears the bag, its invisible but when my friends male character wears the bag, we can see it. ive tried reinstalling my game, deleting and reinstalling all mods and the issue persists. maybe it is something to do with character gender?

**Comment by AColtre** [comment]
This is still happening, I used to have Clothes box redux but I removed it and It's still happening. Only on female characters. 
here is a screenshot and our mod list.
![20221106153010_1](https://user-images.githubusercontent.com/66138747/200180214-541f66f3-4eae-4961-97c1-50bdfbcb22b7.jpg)

modlist: https://steamcommunity.com/sharedfiles/filedetails/?id=2875342940

**Comment by AColtre** [comment]
It's id is Base.Bag_SurvivorBag

**Comment by ShyFemboy4190** [comment]
@AColtre , Hate to be that Guy but could i get the name of the mod for that poster on the right? would be much appreciated, thanks

**Comment by AColtre** [comment]
@ShyFemboy4190 lol, It's the map Grapeseed. You find those around in the town and you pick them up like furniture, I can't remember where exactly.

**Comment by ShyFemboy4190** [comment]
@AColtre , thanks. i appreciate it

**Comment by GoodOldLeon** [comment]
Hi, I'm also having this issue, currently on 41.78. 
Here's a short video I took on a completely fresh save, only mods active are Military uniform improvementes and Necroforge (to spawn the backpack). Hope it helps: https://youtu.be/7qiNq1kBWVw
