### ISSUE TITLE
Alice pack moves out of sync with player's movement

### ISSUE THREAD

**Issue by DaneRedon** [sharkster91/SMUI#28]
I'm not sure if this is a visual glitch on my end but the way the alice pack moves seems out of sync with the rest of the player's movement. It seems to move a lot faster and further than the rest of the body, video below. Thank you for reading!

https://user-images.githubusercontent.com/20031525/189177122-1e8f637c-be1b-4fa1-8a19-7999bbcc0132.mp4

**Comment by sharkster91** [comment]
It isn't out of sync, that is how all backpacks in PZ move as its assigned
to the backpack "bone."

I'll be returning to backpacks as I am busy elsewhere.
