### ISSUE TITLE
Woodland PASGT vest shows vanilla model over modded

### ISSUE THREAD

**Issue by CptHarper** [sharkster91/SMUI#29]
I just noticed when I was gearing up for a loot run the texture on the vest was a little too big like in vanilla, turns out its just the vanilla vest with the modded name, seems like its like that for all woodland ones, Desert Battle/Green/Desert all show their proper modded models.

**Comment by sharkster91** [comment]
This is because you have a mod that is conflicting with it.

**Comment by CptHarper** [comment]
hmmm I see, being im new to zomboid modding for servers, what kinda mods would interfere with a PASGT vest? since everything else in the mod spawns and works to boot, thank you for your help

**Comment by sharkster91** [comment]
Not my position to go bug hunting for the possible 100 mods that can do that.
