### ISSUE TITLE
Disappearing clothes

### ISSUE THREAD

**Issue by Lazimis** [sharkster91/SMUI#36]
Hi i've noticed a problem with one of the helmets(not sure if other helmets do the same) whenever i load a save with PASGT helmet equiped it just disappear from my inventory. Playing for few hours shows no issues but just simply loading saves completly removes the helmet.

**Comment by sharkster91** [comment]
You are being too vague. I need the specific PASGT helmet.

**Comment by Lazimis** [comment]
the helmet disappering is Woodland PASGT helmet with googles. The strapless version is fine but when the strap is on the helmet disappears when loading game.
