### ISSUE TITLE
Large ALICE Pack/ Large Woodland ALICE Pack have the same green texture.

### ISSUE THREAD

**Issue by usncole** [sharkster91/SMUI#44]
No longer see the camo pattern.  I noticed that both items reference the same model in your mod. Is this intentional? The only other clothing mods I use are Brita's and Authentic Z. 

item Bag_LargeALICEPack
    {
        DisplayCategory = Bag,
        Type = Container,
        DisplayName = Large ALICE Pack,
        ClothingItem = Bag_LargeALICEPack,
        CanBeEquipped = Back,
        WeightReduction	=	70,
        Weight	=	3.5,
        Capacity	=	35,
        Icon	=	GreenALICEPack,
        OpenSound   =   OpenBag,
        CloseSound   =   CloseBag,
        PutInSound   =   PutItemInBag,
        BloodLocation = Bag,
        RunSpeedModifier = 2.0,
        CanHaveHoles = false,
        AttachmentReplacement = Bag,
        ReplaceInSecondHand = Bag_ALICEpack_LHand holdingbagleft,
        ReplaceInPrimaryHand = Bag_ALICEpack_RHand holdingbagright,
        Tags = Military,	
        WorldStaticModel = LargeALICEGreen_WorldItem,
    }

        item Bag_LargeALICEPackWoodland
    {
        DisplayCategory = Bag,
        Type = Container,
        DisplayName = Large Woodland ALICE Pack,
        ClothingItem = Bag_LargeALICEPack,
        CanBeEquipped = Back,
        WeightReduction	=	70,
        Weight	=	3.5,
        Capacity	=	35,
        Icon	=	WoodlandALICEPack,
        OpenSound   =   OpenBag,
        CloseSound   =   CloseBag,
        PutInSound   =   PutItemInBag,
        BloodLocation = Bag,
        RunSpeedModifier = 2.0,
        CanHaveHoles = false,
        AttachmentReplacement = Bag,
        ReplaceInSecondHand = Bag_ALICEpack_LHand holdingbagleft,
        ReplaceInPrimaryHand = Bag_ALICEpack_RHand holdingbagright,
        Tags = Military,	
        WorldStaticModel = LargeALICEWoodland_WorldItem,
}

**Comment by sharkster91** [comment]
Show me a screenshot.

**Comment by usncole** [comment]
The code speaks for itself. I made a quick patch to fix the clothing reference and it works fine now. I'll also have to resize the pouches as they're obviously too big. Why even mod if you are going to mark everyone's issues as fixed? Your work is obviously flawed and you can't take the criticism. That's probably why you disabled the comment section on your mod. Grow up.
