### ISSUE TITLE
SLEO Black/Green Leg Pouches floating around leg.

### ISSUE THREAD

**Issue by usncole** [sharkster91/SMUI#45]
I started finding these in my game recently so I'm not sure if it was a recent update, but the pouches appear to hover around the leg as if they were not tightened.  Almost as if the model is slightly too big.

**Comment by sharkster91** [comment]
Any tighter and it's going to begin clipping normal pants.

**Comment by usncole** [comment]
The thing is, it floats above your own military and police outfits so that can't be the reason. I haven't tried to wear them with anything else.
