### ISSUE TITLE
Lag/Fps drop when crafting

### ISSUE THREAD

**Issue by PiechYFL** [sharkster91/SMUI#47]
Hey recently i discorver when mod is enabled when i try tear up cloth i get lag when list of items which can be tear up. I hope you fix it becouse to me lags make game unplayable with mod

Edit 1 Its not mod fault but still i am begging for help

**Comment by vinilol467** [comment]
Also having this issue

**Comment by Kalmorph** [comment]
This is a common issue for when mods adds tons of clothes. It attempts to show which clothes you can rip in the tooltip that shows.

Use this mod and it will stop trying to show that, therefore stop lagging when crafting: https://steamcommunity.com/sharedfiles/filedetails/?id=2898902591
