### ISSUE TITLE
Desert Shirt no texture

### ISSUE THREAD

**Issue by Dendriticcell** [sharkster91/SMUI#49]
Title says it all, disabled all mods besides one that adds in a soldier profession

**Comment by sharkster91** [comment]
Define which "desert shirt" it is.

**Comment by Dendriticcell** [comment]
The rolled down one

**Comment by Dendriticcell** [comment]
Specifically Base.Tshirt_CamoDesert

**Comment by sharkster91** [comment]
I disabled that, you have a mod reenabling that. I will just do something
else with it.
