### ISSUE TITLE
SLEO/SMUI clothing issues

### ISSUE THREAD

**Issue by Switch1870** [sharkster91/SMUI#52]
Since the recent update of SMUI on 10/DEC/2022 @ 8:47pm, I've noticed a few SLEO clothing items have begun breaking.

The bug appears to affect SLEOClothing.ElbowPads, SLEOClothing.KneePads, SLEOClothing.Legholster_Right and SLEOClothing.TacticalGoggles to name but a few.

The items can be added to characters on the Customise Character screen as seen in the first image attached below. However, once you're in-game, the items cannot be interacted with nor removed unless you're using a third-party addon that allows you to unequip items (such as PZ-Clothing UI).

Once unequipped they do not appear in the ground loot context menu on the right side of the UI, but their physical models can be clicked on and grabbed on the ground. Once they're picked up, they simply disappear and don't appear anywhere inside the inventory. In the case of SLEOClothing.LegHolster_Right, the item drops a strangely textured model on the ground before doing the same thing - vanishing.

Using admin tools to make use of the Item Spawner window, when searching for SLEOClothing and trying to add the above-mentioned items, nothing seems to appear in the player inventory. This has been tried with only SLEO/SMUI and their dependencies.

I've also noticed an issue with the Shemagh (All variants) where clicking Pull Up in the context menu results in the Shemagh being worn in the down state, and vice versa. This has been an issue for a while, but of much lower concern as the clothing item functions just fine as it is.

https://i.imgur.com/wKM7Siy.png - items appear in the available clothing lists in the Character Customise screen
https://i.imgur.com/UQKlSwk.png - Items appear on the character model but not the inventory
https://i.imgur.com/qpLdGMw.png - PZ-Clothing UI showing the items as worn at the bottom, but none of the items appear in the main inventory
https://i.imgur.com/wDCll0P.png - SLEOClothing.LegHolster_Right has an untextured item model

**Comment by sharkster91** [comment]
Most of what you have is disabled by default by me but the game seems to be
reenabling. The Elbow Pads, Knee Pads, and Leg Holster are disabled because
I want to rework them later.

I'll look at everything else later.

**Comment by Switch1870** [comment]
Ahh, awesome. Thanks for the quick reply Shark.
