### ISSUE TITLE
Items Don't Show

### ISSUE THREAD

**Issue by Dread-Wolf** [sharkster91/SMUI#55]
No matter what I do, I can't seem to get this mod working on my server.  It appears to load correctly, shows in the active mods while in game, but no items show up and if I go into admin mode, SLEO/SMUI are both missing from the items list.  Shark's weapons is working correctly.  I've been wracking my brain over this for several days and can't find the culprit.

**Comment by Dread-Wolf** [comment]
I should comment that I've used this mod successfully in the past on a dedicated MP server so it isn't that I don't know how to properly install mods.  Something is happening that is causing the issue.  I can't identify any mod conflicts so that's what I'm posting here.

**Comment by sharkster91** [comment]
I am not huge on doing server support, but you could be missing the mod
ID's in your server.ini file which is preventing the mods from loading.

**Comment by Dread-Wolf** [comment]
Totally understand and definitely not asking you to do server support.  I more wanted to report it in case it was a bug you start noticing.  I have checked the .ini file multiple times to ensure I'd got the mod names and IDs in there. The only thing I've noticed is that the belt item comes up with a blank tooltip and causes errors but when I look, it says it is stemming from the skill recovery journal mod.  Obviously, not your baby, but I did report that there as well.  I'm unsure if the error from that mod is causing a conflict with your mods.  Just weird that I never ran into it before a few weeks ago.  SMUI, SLEO and that all ran perfectly fine until recently.  I appreciate you responding, I hope you have a great holiday.

**Comment by sharkster91** [comment]
I'll look it all over again, thanks. Merry Christmas.

**Comment by RoryNorman** [comment]
I can also confirm, I have used this on a server 9 months ago successfully, but the server I started in the last 2 weeks it is not showing. ID and mod name are correctly set in the INI, and it downloads the content for the server successfully. It just isn't overwriting the base game items and spawning in game at all.
