### ISSUE TITLE
Invisible Police Cap

### ISSUE THREAD

**Issue by Xerionus** [sharkster91/SMUI#60]
![Project Zomboid Screenshot 2022 12 30 - 16 26 54 58](https://user-images.githubusercontent.com/121682348/210087133-f8a69324-0f83-4f1d-bafd-0942763adf06.png)
Just as with Alice backpack. Police Cap seems to be invisible as well.

**Comment by sharkster91** [comment]
This is fine on my end.

**Comment by Xerionus** [comment]
I'm not really experienced in modding to be arguing, but how? I literally went again and disabled all my mods except SMUI and SLEO and the Police Cap was invisible only on female.

**Comment by sharkster91** [comment]
This isn't an argument and I am not entirely discounting what you are
saying. I have cleaning to do in both mods as I entirely discounted females
and I will be doing this at the beginning of the New Year.

**Comment by Xerionus** [comment]
Alright all's clear.
