### ISSUE TITLE
Latest update on 4th January broke Tidy Up Meister

### ISSUE THREAD

**Issue by Tofuman89** [sharkster91/SMUI#67]
Hello there,

After updating to the latest version of the mod, Tidy Up Meister doesn't work with the mod. Items are not returned back to where it belongs. Can confirm with only SMUI enabled and Tidy Up Meister enabled. So far no stack trace error in the log.

Hope you look into this,

Cheers!

**Comment by a56444c** [comment]
I'm having the same issue.
