### ISSUE TITLE
SMUI update bugged some items

### ISSUE THREAD

**Issue by DevoTan** [sharkster91/SMUI#71]
Seems with the latest update a bunch of items from SMUI are missing their .XML files. I've attached a file with a copy of all of the errors I encountered while starting my server with this mod loaded.
[SMUIErrorLog.txt](https://github.com/sharkster91/SMUI/files/11523857/SMUIErrorLog.txt)

**Comment by sharkster91** [comment]
Yes, and this mod is now inactive. I am busy combining both mods.
